/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iliyas
 */

import javax.swing.JOptionPane;
import com.mysql.jdbc.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class BookTicket extends javax.swing.JFrame {

    
        Connection conn = null;
     PreparedStatement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form BookTicket
     */
   
String pid,pname,depcity,arrcity,noseats,btype,dojstring,fare,amount,busno;
Date doj;
     int dialogResult = 0;
     int dialogButton = JOptionPane.YES_NO_OPTION;
private  void date()
{
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate localDate = LocalDate.now();
//System.out.println(dtf.format(localDate));
//2016/11/16
DateLabel.setText(dtf.format(localDate));
}

 public boolean updateSeats(int seats, String bid) {
        
     
     try {
            conn = MysqlConnect.connectDB();
            ps=conn.prepareStatement("SELECT * FROM bus where bus_no = ?");
            ps.setString(1,bid);
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                
                int rseats =(rs.getInt("no_seats"));
                
                //int noseats = (rs.getInt("num_seats"));
                     
            
                if (seats<=rseats) {
                    int newSeat = rseats - seats;
                    try
                    {
                            
                         ps=conn.prepareStatement("UPDATE BUS set no_seats = ? where bus_no = ?");        
                        ps.setString(2,bid);
                        ps.setInt(1,newSeat);
                        ps.execute();
                    }
                    catch (Exception e)
                            {
                                JOptionPane.showMessageDialog(null,"Error "+e);
                            }
                    return true;
                }
                else{
                    JOptionPane.showMessageDialog(null, seats+" Seats not available");
                    return false;
                }
            }
        
        } catch (Exception e) {
           e.printStackTrace();
        }
        return false;
    }

    private void fillCombo(){
    try
        {
             conn = MysqlConnect.connectDB();
            ps=conn.prepareStatement("SELECT * FROM passenger");        
            rs = ps.executeQuery();
 
            while(rs.next())
            {
                String pid = (rs.getString("id"));
                IDCombobox.addItem(pid);                    
            } 
            
            conn.close();
      
           }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
    public BookTicket() {
        initComponents();
        fillCombo();
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GetFare = new javax.swing.JButton();
        IDCombobox = new javax.swing.JComboBox<>();
        FromCombobox = new javax.swing.JComboBox<>();
        ToCombobox = new javax.swing.JComboBox<>();
        FareTextbox = new javax.swing.JTextField();
        TotalTextbox = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jLable11 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DOJ = new com.toedter.calendar.JDateChooser();
        BusNoTextbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PNameTextbox = new javax.swing.JTextField();
        NoSeatsCombobox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        BusTypeCombobox = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        HeadLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking::Book Ticket");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        BookButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        BookButton.setText("BOOK");
        BookButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BookButton);
        BookButton.setBounds(410, 590, 160, 40);

        CancelButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(600, 590, 150, 40);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of Seats:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 290, 200, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 240, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 240, 40, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("passenger ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 130, 160, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Journey :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 350, 180, 40);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fare per Seat : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 450, 170, 40);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Amount to be paid : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 490, 270, 40);

        GetFare.setBackground(new java.awt.Color(102, 255, 0));
        GetFare.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        GetFare.setText("GET FARE");
        GetFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetFareActionPerformed(evt);
            }
        });
        getContentPane().add(GetFare);
        GetFare.setBounds(360, 400, 150, 40);

        IDCombobox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IDCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IDComboboxItemStateChanged(evt);
            }
        });
        IDCombobox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                IDComboboxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        IDCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(IDCombobox);
        IDCombobox.setBounds(360, 130, 150, 30);

        FromCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUNE", "MUMBAI", "DELHI", "AGRA", "HYDERABAD"}));
        getContentPane().add(FromCombobox);
        FromCombobox.setBounds(360, 240, 150, 30);

        ToCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUNE", "MUMBAI", "DELHI", "AGRA", "HYDERABAD" }));
        ToCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(ToCombobox);
        ToCombobox.setBounds(690, 240, 120, 30);

        FareTextbox.setEditable(false);
        getContentPane().add(FareTextbox);
        FareTextbox.setBounds(360, 460, 150, 30);

        TotalTextbox.setEditable(false);
        getContentPane().add(TotalTextbox);
        TotalTextbox.setBounds(360, 500, 150, 30);

        GenderLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(GenderLabel);
        GenderLabel.setBounds(690, 180, 100, 30);

        DateLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(DateLabel);
        DateLabel.setBounds(690, 130, 130, 30);

        jLable11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLable11.setForeground(new java.awt.Color(255, 255, 255));
        jLable11.setText("Bus No. :");
        getContentPane().add(jLable11);
        jLable11.setBounds(540, 470, 100, 70);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 130, 70, 30);

        DOJ.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(DOJ);
        DOJ.setBounds(360, 340, 150, 30);

        BusNoTextbox.setEditable(false);
        BusNoTextbox.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BusNoTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusNoTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(BusNoTextbox);
        BusNoTextbox.setBounds(660, 460, 210, 70);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Passenger Name : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 180, 190, 30);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 180, 100, 30);

        PNameTextbox.setEditable(false);
        PNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNameTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(PNameTextbox);
        PNameTextbox.setBounds(360, 180, 150, 30);

        NoSeatsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(NoSeatsCombobox);
        NoSeatsCombobox.setBounds(360, 290, 150, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bus Type :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(550, 300, 110, 30);

        BusTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC","NON-AC"}));
        BusTypeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusTypeComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(BusTypeCombobox);
        BusTypeCombobox.setBounds(690, 300, 120, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton5.setText("<< BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 50, 130, 60);

        HeadLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel.setText("                        BUS RESERVATION SYSTEM");
        HeadLabel.setOpaque(true);
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(0, 0, 1080, 40);

        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("BOOK TICKETS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 60, 280, 54);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        Background.setAlignmentY(0.0F);
        Background.setName("background"); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNameTextboxActionPerformed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_PNameTextboxActionPerformed
 
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        new Choice().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BusTypeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusTypeComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusTypeComboboxActionPerformed

    private void IDComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDComboboxActionPerformed

       


    }//GEN-LAST:event_IDComboboxActionPerformed

    private void GetFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetFareActionPerformed
       
       pid=(String)IDCombobox.getSelectedItem();
       btype=(String)BusTypeCombobox.getSelectedItem();
       depcity=(String)FromCombobox.getSelectedItem();
       arrcity=(String)ToCombobox.getSelectedItem();
       pname=PNameTextbox.getText();
       noseats=(String)NoSeatsCombobox.getSelectedItem();
       fare=FareTextbox.getText();
       amount=TotalTextbox.getText();
       
           try {
                    conn = MysqlConnect.connectDB();
            String depcity=(String)FromCombobox.getSelectedItem();
            String arrcity=(String)ToCombobox.getSelectedItem();
            String type=(String)BusTypeCombobox.getSelectedItem();
           //conn = MysqlConnect.connectDB();
           
         java.util.Date dojdate=DOJ.getDate();
                    SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        dojstring = dformat.format(dojdate);
             pid=(String)IDCombobox.getSelectedItem();
            btype=(String)BusTypeCombobox.getSelectedItem();
            depcity=(String)FromCombobox.getSelectedItem();
            arrcity=(String)ToCombobox.getSelectedItem();
            pname=PNameTextbox.getText();
            noseats=(String)NoSeatsCombobox.getSelectedItem();
            fare=FareTextbox.getText();
             amount=TotalTextbox.getText();
                   
                 
            ps=conn.prepareStatement("SELECT * FROM bus where dep_city = ? and arr_city = ? and bus_type=? and dep_date=?");
            ps.setString(1,depcity);
            ps.setString(2,arrcity);
            ps.setString(3,type);
            ps.setString(4,dojstring);
            rs = ps.executeQuery();
//            if (false)
//            {
//            JOptionPane.showMessageDialog(null, "Bus matching your criteria is not available");
//            }
//            else
            if(rs.next())    
            {    
                int fare = rs.getInt(11);
                String farestring=rs.getString(11);
                
                
                String busno=rs.getString(1);
            
                String noseatstring=(String)NoSeatsCombobox.getSelectedItem();
                int noseats = Integer.parseInt(noseatstring);
                int amount = fare * noseats;
               
               
                double dis = 0;
                if (amount >= 1000 && amount <= 2000) {
                    dis = amount * 0.05;
                } else if (amount > 2000 && amount <= 3000) {
                    dis = amount * 0.10;
                } else if (amount > 3000 && amount <= 5000) {
                    dis = amount * 0.15;
                } else if (amount > 4000) {
                    dis = amount * 0.20;
                }
                amount = (int) (amount - dis);
               
                    if(updateSeats(noseats,busno))
                {
                BusNoTextbox.setText(busno);
                FareTextbox.setText(farestring);
                TotalTextbox.setText(amount + "");
                }
                }
            else
            {
                       JOptionPane.showMessageDialog(null, "Bus matching your criteria is not available");
            }
               
           } 
           catch (Exception e)
           {
            JOptionPane.showMessageDialog(null, "Fill All Details");
            //e.printStackTrace();
             }
           
        

// TODO add your handling code here:
    }//GEN-LAST:event_GetFareActionPerformed

    private void IDComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IDComboboxItemStateChanged
   
         // TODO add your handling code here:
    }//GEN-LAST:event_IDComboboxItemStateChanged

    private void IDComboboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_IDComboboxPopupMenuWillBecomeInvisible
        String gidstring=(String)IDCombobox.getSelectedItem();
        String sql="SELECT * FROM passenger where id = ?";
    try 
    {
        conn = MysqlConnect.connectDB();
            
            
            int gid = Integer.parseInt(gidstring);
            ps=conn.prepareStatement(sql);        
            ps.setInt(1,gid);
            rs = ps.executeQuery();
            if(rs.next())
            {   
             //IDCombobox.addItem(rs.getString(1));
            String fname = (rs.getString(2));
            String mname = (rs.getString(3));
            String lname = (rs.getString(4));
            String gender = (rs.getString("gender"));
            String name = fname+" "+mname+" "+lname;
            PNameTextbox.setText(name);
            GenderLabel.setText(gender);
    }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_IDComboboxPopupMenuWillBecomeInvisible

    private void BusNoTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusNoTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNoTextboxActionPerformed

    private void ToComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToComboboxActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
            conn = MysqlConnect.connectDB();
        String tidstring,pidstring,pnamestring,bid,amountstring,noseatsstring,bdatestring,fromstring,tostring,btypestring;
       int tid = 0,pid,amount,noseats;
        
        pidstring=(String)IDCombobox.getSelectedItem();
        pnamestring=PNameTextbox.getText();
       bid=BusNoTextbox.getText();
       amountstring=TotalTextbox.getText();
       noseatsstring=(String)NoSeatsCombobox.getSelectedItem();
       fromstring=(String)FromCombobox.getSelectedItem();
       tostring=(String)ToCombobox.getSelectedItem();
       btypestring=(String)BusTypeCombobox.getSelectedItem();
             
        
        if(pidstring.isEmpty()||pnamestring.isEmpty()||bid.isEmpty()||amountstring.isEmpty()||btypestring.isEmpty()||
               noseatsstring.isEmpty()||fromstring.isEmpty()||tostring.isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Please Fill all fields before Booking", "Error", JOptionPane.ERROR_MESSAGE);
       }
       
       else
        {
             dialogResult = JOptionPane.showConfirmDialog (null, "Click YES if you are ready to book ticket ?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
        
       try
        {
               
            //tid= Integer.parseInt(tidstring);
            pid= Integer.parseInt(pidstring);
            amount= Integer.parseInt(amountstring);
            noseats= Integer.parseInt(noseatsstring);
               java.util.Date dojdate=DOJ.getDate();
                SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String dojstring = dformat.format(dojdate);
            Calendar calendar = Calendar.getInstance();
            java.util.Date currentDate = calendar.getTime();
            java.sql.Date dob = new java.sql.Date(currentDate.getTime());
       String dobstring = dformat.format(dob);
            
             if(updateSeats(noseats,bid))
       {
            String sql= "INSERT INTO ticket VALUES(?,?,?,?,?,?,?)";
            ps=conn.prepareStatement(sql);        
            ps.setInt(1,0);
            ps.setInt(2,pid);
            ps.setString(3,bid);
            ps.setString(4,dobstring);
            ps.setInt(5,noseats);
            ps.setString(6,dojstring);
            ps.setInt(7,amount);
            ps.execute();
                        
            {
            IDCombobox.setSelectedItem(null);
            BusNoTextbox.setText(null);
            DateLabel.setText(null);
            GenderLabel.setText(null);
            PNameTextbox.setText(null);
            DOJ.setDate(null);
            NoSeatsCombobox.setSelectedItem(null);
            FromCombobox.setSelectedItem(null);
            ToCombobox.setSelectedItem(null);
            BusTypeCombobox.setSelectedItem(null);
            FareTextbox.setText(null);
            TotalTextbox.setText(null);
            }
            try
                {
                    ps=conn.prepareStatement("SELECT MAX(ticket_id) from ticket");
           
                     rs = ps.executeQuery();
                     if(rs.next())
                     {
                         tid = rs.getInt(1);
                     JOptionPane.showMessageDialog(null,"Thank You!! Your Ticket has been booked Successfuly."
                             + "Your Ticket ID is : "+Integer.toString(tid));
                       
                        new PrintTicket().setVisible(true);
                        this.setVisible(false);
                     }
                }
                catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null, e);
                }
            conn.close();
       }
            
      }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BookButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
           
         dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to cancel this Booking ?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
        
         IDCombobox.setSelectedItem(null);
            BusNoTextbox.setText(null);
            GenderLabel.setText(null);
            PNameTextbox.setText(null);
            DOJ.setDate(null);
            NoSeatsCombobox.setSelectedItem(null);
            FromCombobox.setSelectedItem(null);
            ToCombobox.setSelectedItem(null);
            BusTypeCombobox.setSelectedItem(null);
            FareTextbox.setText(null);
            TotalTextbox.setText(null);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BookButton;
    private javax.swing.JTextField BusNoTextbox;
    public javax.swing.JComboBox<String> BusTypeCombobox;
    private javax.swing.JButton CancelButton;
    private com.toedter.calendar.JDateChooser DOJ;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField FareTextbox;
    public javax.swing.JComboBox<String> FromCombobox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton GetFare;
    private javax.swing.JLabel HeadLabel;
    public javax.swing.JComboBox<String> IDCombobox;
    private javax.swing.JComboBox<String> NoSeatsCombobox;
    private javax.swing.JTextField PNameTextbox;
    public javax.swing.JComboBox<String> ToCombobox;
    private javax.swing.JTextField TotalTextbox;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable11;
    // End of variables declaration//GEN-END:variables
}
