
import java.awt.event.ActionEvent;
import com.mysql.jdbc.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iliyas
 */
public class BusManagement extends javax.swing.JFrame {
    Connection conn= null;
    PreparedStatement ps=null;
    ResultSet rs=null;

           int dialogResult = 0;
     int dialogButton = JOptionPane.YES_NO_OPTION;
       String busno,btype,depcity,depdatestring,arrcity,deptime,arrtime,noseatsstring,farestring,distancestring;
       int noseats,fare,distance;
       Date depdate;
       //Date depdate;
       String Vemail = "^[A-Za-z0-9+_.-]+@(.+)$";
       String Vname="[a-zA-Z]*";
       String Vno="[0-9]*";
       String Vbusno = "[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{4}$";
       String Vtime ="^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$";
       
       /**
     * Creates new form BusManagement
     */
    public BusManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BusNoTextbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TypeCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NoSeatsTextbox = new javax.swing.JTextField();
        DepCityCombobox = new javax.swing.JComboBox<>();
        DistanceTextbox = new javax.swing.JTextField();
        FareTextbox = new javax.swing.JTextField();
        ArrCityCombobox = new javax.swing.JComboBox<>();
        DisplayButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        DepDate = new com.toedter.calendar.JDateChooser();
        viewdetailsbuttonfield = new javax.swing.JToggleButton();
        DepTimeTextbox = new javax.swing.JTextField();
        ArrTimeTextbox = new javax.swing.JTextField();
        busmessage = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        HeadLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking::Bus Management");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bus Registration Number :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 130, 200, 40);

        BusNoTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusNoTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(BusNoTextbox);
        BusNoTextbox.setBounds(400, 130, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bus Type :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 190, 90, 30);

        TypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        getContentPane().add(TypeCombobox);
        TypeCombobox.setBounds(400, 190, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Max Number of seats :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 240, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departure City :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 300, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arrival City :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 300, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departure Time :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 350, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Arrival Time :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 350, 100, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Distance in KM. :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 410, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fare :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 460, 40, 30);

        NoSeatsTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoSeatsTextboxActionPerformed(evt);
            }
        });
        NoSeatsTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoSeatsTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(NoSeatsTextbox);
        NoSeatsTextbox.setBounds(400, 250, 140, 30);

        DepCityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUNE", "MUMBAI", "DELHI", "AGRA", "HYDERABAD" }));
        DepCityCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepCityComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(DepCityCombobox);
        DepCityCombobox.setBounds(400, 300, 140, 40);

        DistanceTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanceTextboxActionPerformed(evt);
            }
        });
        DistanceTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DistanceTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(DistanceTextbox);
        DistanceTextbox.setBounds(690, 410, 140, 30);

        FareTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FareTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(FareTextbox);
        FareTextbox.setBounds(400, 460, 140, 30);

        ArrCityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"PUNE", "MUMBAI", "DELHI", "AGRA", "HYDERABAD" }));
        getContentPane().add(ArrCityCombobox);
        ArrCityCombobox.setBounds(690, 300, 140, 40);

        DisplayButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        DisplayButton.setText("DISPLAY");
        DisplayButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayButton);
        DisplayButton.setBounds(560, 560, 130, 40);

        AddButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        AddButton.setText("ADD");
        AddButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(250, 560, 120, 40);

        ModifyButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        ModifyButton.setText("Update");
        ModifyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton);
        ModifyButton.setBounds(400, 560, 130, 40);

        DeleteButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton);
        DeleteButton.setBounds(730, 560, 130, 40);

        DepDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(DepDate);
        DepDate.setBounds(400, 410, 140, 30);

        viewdetailsbuttonfield.setText("VIEW DETAILS");
        viewdetailsbuttonfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewdetailsbuttonfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsbuttonfieldActionPerformed(evt);
            }
        });
        getContentPane().add(viewdetailsbuttonfield);
        viewdetailsbuttonfield.setBounds(580, 130, 110, 40);

        DepTimeTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepTimeTextboxActionPerformed(evt);
            }
        });
        DepTimeTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DepTimeTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(DepTimeTextbox);
        DepTimeTextbox.setBounds(400, 360, 140, 30);

        ArrTimeTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrTimeTextboxActionPerformed(evt);
            }
        });
        ArrTimeTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ArrTimeTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(ArrTimeTextbox);
        ArrTimeTextbox.setBounds(690, 360, 140, 30);

        busmessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busmessage.setForeground(new java.awt.Color(255, 255, 255));
        busmessage.setText("Enter Bus number in this format : MH12BH6444");
        getContentPane().add(busmessage);
        busmessage.setBounds(300, 170, 350, 20);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton5.setText("<< BACK");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 50, 130, 60);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Departure Date :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 400, 120, 40);

        HeadLabel1.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel1.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel1.setText("                        BUS RESERVATION SYSTEM");
        HeadLabel1.setOpaque(true);
        getContentPane().add(HeadLabel1);
        HeadLabel1.setBounds(0, 0, 1080, 40);

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("BUS MANAGEMENT");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 70, 320, 54);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        Background.setAlignmentY(0.0F);
        Background.setName("background"); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DistanceTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanceTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceTextboxActionPerformed

    private void DepCityComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCityComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCityComboboxActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        
        conn = MysqlConnect.connectDB();
        
        busno=BusNoTextbox.getText();
        btype=(String)TypeCombobox.getSelectedItem();  
        depcity=(String)DepCityCombobox.getSelectedItem();
        arrcity=(String)ArrCityCombobox.getSelectedItem();
        deptime=DepTimeTextbox.getText();
        arrtime=ArrTimeTextbox.getText();
        //depdate=DepDateTextbox.getText();
        farestring=FareTextbox.getText();  

        distancestring= DistanceTextbox.getText();
         noseatsstring=NoSeatsTextbox.getText();
    
        if(busno.isEmpty()||!busno.matches(Vbusno))
        {
            JOptionPane.showMessageDialog(this,"Enter Bus Number in correct format like MH12AA1234","Alert",JOptionPane.WARNING_MESSAGE);
        }
//        else if((busno.isEmpty())||(btype.isEmpty())||(noseatsstring.isEmpty())||(depcity.isEmpty())||(arrcity.isEmpty())||(deptime.isEmpty())||(arrtime.isEmpty())||(distancestring.isEmpty())||(farestring.isEmpty()))
//        {
//            JOptionPane.showMessageDialog(this,"Please Fill All Fields !!","Alert",JOptionPane.WARNING_MESSAGE);
//        }
         else if(noseatsstring.isEmpty()||!(noseatsstring.matches(Vno))||(noseatsstring.length()>2)||"0".equals(noseatsstring))
        {
           JOptionPane.showMessageDialog(this,"Enter No of seats between 1 to 100 !!","Alert",JOptionPane.WARNING_MESSAGE);
        }
         else if(depcity==arrcity)
        {
            JOptionPane.showMessageDialog(this,"Departure City and Arrival City cannot be same !!","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(!deptime.matches(Vtime)||!arrtime.matches(Vtime))
        {
            JOptionPane.showMessageDialog(this,"Enter Time in Correct Format like HH:mm:ss ","Alert",JOptionPane.WARNING_MESSAGE);
        }
       
        else if(!(distancestring.matches(Vno)))
                {
                    JOptionPane.showMessageDialog(this,"Enter Distance using only NUMBERS !!","Alert",JOptionPane.WARNING_MESSAGE);
                }     
        
        else if(!(farestring.matches(Vno)))
                {
                    JOptionPane.showMessageDialog(this,"Enter Fare using only NUMBERS !!","Alert",JOptionPane.WARNING_MESSAGE);
                }
       
       else
        { 
            dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure yo add this bus details ?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
        try{
             fare= Integer.parseInt(farestring);
            distance= Integer.parseInt(DistanceTextbox.getText());
            noseats = Integer.parseInt(noseatsstring);
                 java.util.Date depdate=DepDate.getDate();
                    SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        depdatestring = dformat.format(depdate);
            
            String sql= "INSERT INTO bus VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            ps=conn.prepareStatement(sql);        
            ps.setString(1,busno);
            ps.setString(2,btype);
            ps.setInt(3,noseats);
            ps.setInt(4,noseats);
            ps.setString(5,depcity);
            ps.setString(6,arrcity);
            ps.setString(7,depdatestring);
            ps.setString(8,deptime);
           ps.setString(9,arrtime);
         ps.setInt(10,distance);
          ps.setInt(11,fare);
            
            ps.execute();
            {
                JOptionPane.showMessageDialog(null,"Bus Details Added Successfully");                       
                TypeCombobox.setSelectedItem(1);
                BusNoTextbox.setText(null);
                DepCityCombobox.setSelectedItem(1);
                ArrCityCombobox.setSelectedItem(1);
                DepDate.setDate(null);
                DepTimeTextbox.setText(null);
                ArrTimeTextbox.setText(null);
                FareTextbox.setText(null);
                DistanceTextbox.setText(null);
                NoSeatsTextbox.setText(null);
            }
            conn.close();
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Bus Number Already Exists!!","Alert",JOptionPane.WARNING_MESSAGE);
                }
        }
        }// TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        new Choice().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DepTimeTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepTimeTextboxActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_DepTimeTextboxActionPerformed

    private void viewdetailsbuttonfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsbuttonfieldActionPerformed
        // TODO add your handling code here:

        conn = MysqlConnect.connectDB();
        String busno = BusNoTextbox.getText();
         if(busno.isEmpty()||!busno.matches(Vbusno))
        {
            JOptionPane.showMessageDialog(this,"Enter Bus Number in correct format like MH12AA1234","Alert",JOptionPane.WARNING_MESSAGE);
        }
       else
        try
        {
            //String gid = PassengerID.getText();
            // ps = conn.prepareStatement("select * from Passenger where id = 1 ");
            //ps.setString(1,1);
            //String sql = "SELECT * FROM passenger WHERE id = ? ";
            String gid = BusNoTextbox.getText();
            ps=conn.prepareStatement("SELECT * FROM bus WHERE bus_no = ?");
            ps.setString(1,gid);
            rs = ps.executeQuery();
            if(rs.next())
            {

                TypeCombobox.setSelectedItem(rs.getString(2));
                 NoSeatsTextbox.setText(rs.getString(3));
                DepCityCombobox.setSelectedItem(rs.getString(5));
                ArrCityCombobox.setSelectedItem(rs.getString(6));
                DepDate.setDate(rs.getDate(7));
                DepTimeTextbox.setText(rs.getString(8));
                ArrTimeTextbox.setText(rs.getString(9));
                DistanceTextbox.setText(rs.getString(10));
                FareTextbox.setText(rs.getString(11));
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewdetailsbuttonfieldActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        
        
        conn = MysqlConnect.connectDB();
         String busno = BusNoTextbox.getText();
        if(busno.isEmpty()||!busno.matches(Vbusno))
        {
          JOptionPane.showMessageDialog(this,"Enter Bus Number in correct format like MH12AA1234","Alert",JOptionPane.WARNING_MESSAGE);
        }
       else  
         {  
            try
            {
            //String gid = PassengerID.getText();
           // ps = conn.prepareStatement("select * from Passenger where id = 1 ");
            //ps.setString(1,1);
            //String sql = "SELECT * FROM passenger WHERE id = ? ";
            String bid = BusNoTextbox.getText();
            ps=conn.prepareStatement("SELECT * FROM bus WHERE bus_no = ?");        
            ps.setString(1,bid);
            rs = ps.executeQuery();        
            if(rs.next())
                {   
              dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to remove Bus details ?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION)
                 try
                     {  
            String sql = "DELETE FROM bus WHERE bus_no = ? ";
            ps=conn.prepareStatement(sql);        
            ps.setString(1,BusNoTextbox.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null,"Bus details Deleted Successfuly", "Error", JOptionPane.ERROR_MESSAGE);
            TypeCombobox.setSelectedItem(1);
                BusNoTextbox.setText(null);
                DepCityCombobox.setSelectedItem(1);
                ArrCityCombobox.setSelectedItem(1);
                DepDate.setDate(null);
                DepTimeTextbox.setText(null);
                ArrTimeTextbox.setText(null);
                FareTextbox.setText(null);
                DistanceTextbox.setText(null);
                NoSeatsTextbox.setText(null);
                        }
                catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                  else
                    {
                JOptionPane.showMessageDialog(null,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }
            catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                    }
         }
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonActionPerformed
        new DisplayBus().setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_DisplayButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
         conn = MysqlConnect.connectDB();
        
        busno=BusNoTextbox.getText();
        btype=(String)TypeCombobox.getSelectedItem();  
        depcity=(String)DepCityCombobox.getSelectedItem();
        arrcity=(String)ArrCityCombobox.getSelectedItem();
        deptime=DepTimeTextbox.getText();
        arrtime=ArrTimeTextbox.getText();
        //depdate=DepDateTextbox.getText();
        farestring=FareTextbox.getText();  

        distancestring= DistanceTextbox.getText();
         noseatsstring=NoSeatsTextbox.getText();
    
         if(busno.isEmpty()||!busno.matches(Vbusno))
        {
            JOptionPane.showMessageDialog(this,"Enter Bus Number in correct format like MH12AA1234","Alert",JOptionPane.WARNING_MESSAGE);
        }
//        else if((busno.isEmpty())||(btype.isEmpty())||(noseatsstring.isEmpty())||(depcity.isEmpty())||(arrcity.isEmpty())||(deptime.isEmpty())||(arrtime.isEmpty())||(distancestring.isEmpty())||(farestring.isEmpty()))
//        {
//            JOptionPane.showMessageDialog(this,"Please Fill All Fields !!","Alert",JOptionPane.WARNING_MESSAGE);
//        }
         else if(noseatsstring.isEmpty()||!(noseatsstring.matches(Vno))||(noseatsstring.length()>2)||"0".equals(noseatsstring))
        {
           JOptionPane.showMessageDialog(this,"Enter No of seats between 1 to 100 !!","Alert",JOptionPane.WARNING_MESSAGE);
        }
         else if(depcity==arrcity)
        {
            JOptionPane.showMessageDialog(this,"Departure City and Arrival City cannot be same !!","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(!deptime.matches(Vtime)||!arrtime.matches(Vtime))
        {
            JOptionPane.showMessageDialog(this,"Enter Time in Correct Format like HH:mm:ss ","Alert",JOptionPane.WARNING_MESSAGE);
        }
       
        else if(!(distancestring.matches(Vno)))
                {
                    JOptionPane.showMessageDialog(this,"Enter Distance using only NUMBERS !!","Alert",JOptionPane.WARNING_MESSAGE);
                }     
        
        else if(!(farestring.matches(Vno)))
                {
                    JOptionPane.showMessageDialog(this,"Enter Fare using only NUMBERS !!","Alert",JOptionPane.WARNING_MESSAGE);
                }
         
       else
          
         {  
            try
            {
            //String gid = PassengerID.getText();
           // ps = conn.prepareStatement("select * from Passenger where id = 1 ");
            //ps.setString(1,1);
            //String sql = "SELECT * FROM passenger WHERE id = ? ";
            String bid = BusNoTextbox.getText();
            ps=conn.prepareStatement("SELECT * FROM bus WHERE bus_no = ?");        
            ps.setString(1,bid);
            rs = ps.executeQuery();        
            if(rs.next())
                {   
              dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to remove Bus details ?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION)
          
            try{
             fare= Integer.parseInt(farestring);
            distance= Integer.parseInt(DistanceTextbox.getText());
            noseats = Integer.parseInt(noseatsstring);
                 java.util.Date depdate=DepDate.getDate();
                    SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        depdatestring = dformat.format(depdate);
            String sql= "Update bus set bus_type=? , no_seats=? , dep_city = ? , arr_city = ?, dep_date = ?, dep_time=?, arr_time=?,distance=?,fare=?,max_seats=? where bus_no = ? ";
            ps=conn.prepareStatement(sql);        
            ps.setString(11,busno);
            ps.setString(1,btype);
            ps.setInt(2,noseats);
            ps.setInt(10,noseats);
            ps.setString(3,depcity);
            ps.setString(4,arrcity);
            ps.setString(5,depdatestring);
            ps.setString(6,deptime);
           ps.setString(7,arrtime);
         ps.setInt(8,distance);
          ps.setInt(9,fare);
            
            ps.execute();
            {
                JOptionPane.showMessageDialog(null,"Bus Details Updated Successfully");                       
                TypeCombobox.setSelectedItem(1);
                BusNoTextbox.setText(null);
                DepCityCombobox.setSelectedItem(1);
                ArrCityCombobox.setSelectedItem(1);
                DepDate.setDate(null);
                DepTimeTextbox.setText(null);
                ArrTimeTextbox.setText(null);
                FareTextbox.setText(null);
                DistanceTextbox.setText(null);
                NoSeatsTextbox.setText(null);
            }
            conn.close();
        }
        catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                  else
                    {
                JOptionPane.showMessageDialog(null,"Bus Details Not Found.Please Check Bus Number before Updating.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }
            catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                    }
         }
// TODO add your handling code here:
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void ArrTimeTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrTimeTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrTimeTextboxActionPerformed

    private void NoSeatsTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoSeatsTextboxKeyTyped
        
         char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        evt.consume();
                    }
// TODO add your handling code here:
    }//GEN-LAST:event_NoSeatsTextboxKeyTyped

    private void FareTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FareTextboxKeyTyped
       
         char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        evt.consume();
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_FareTextboxKeyTyped

    private void NoSeatsTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoSeatsTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoSeatsTextboxActionPerformed

    private void DistanceTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DistanceTextboxKeyTyped

         char vChar = evt.getKeyChar();
                    if (!(Character.isDigit(vChar)
                            || (vChar == KeyEvent.VK_BACK_SPACE)
                            || (vChar == KeyEvent.VK_DELETE))) {
                        evt.consume();
                    }
// TODO add your handling code here:
    }//GEN-LAST:event_DistanceTextboxKeyTyped

    private void BusNoTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusNoTextboxKeyTyped
        
         char keyChar = evt.getKeyChar();
    if (Character.isLowerCase(keyChar)) {
      evt.setKeyChar(Character.toUpperCase(keyChar));
    }
// TODO add your handling code here:
    }//GEN-LAST:event_BusNoTextboxKeyTyped

    private void DepTimeTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepTimeTextboxKeyTyped
       
//           char vChar = evt.getKeyChar();
//                    if (!(Character.isDigit(vChar)
//                            || (vChar == KeyEvent.VK_BACK_SPACE)
//                            || (vChar == KeyEvent.VK_DELETE))) {
//                        evt.consume();
//                    }

// TODO add your handling code here:
    }//GEN-LAST:event_DepTimeTextboxKeyTyped

    private void ArrTimeTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArrTimeTextboxKeyTyped
       
//        char vChar = evt.getKeyChar();
//                    if (!(Character.isDigit(vChar)
//                            || (vChar == KeyEvent.VK_BACK_SPACE)
//                            || (vChar == KeyEvent.VK_DELETE)
//                            || (vChar == KeyEvent.VK_COLON))) {
//                        evt.consume();
//                    }
       // TODO add your handling code here:
    }//GEN-LAST:event_ArrTimeTextboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> ArrCityCombobox;
    private javax.swing.JTextField ArrTimeTextbox;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField BusNoTextbox;
    private javax.swing.JButton DeleteButton;
    public javax.swing.JComboBox<String> DepCityCombobox;
    private com.toedter.calendar.JDateChooser DepDate;
    private javax.swing.JTextField DepTimeTextbox;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JTextField DistanceTextbox;
    private javax.swing.JTextField FareTextbox;
    private javax.swing.JLabel HeadLabel1;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NoSeatsTextbox;
    private javax.swing.JComboBox<String> TypeCombobox;
    private javax.swing.JLabel busmessage;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton viewdetailsbuttonfield;
    // End of variables declaration//GEN-END:variables
}
