/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iliyas
 */
public class Choice extends javax.swing.JFrame {

    /**
     * Creates new form Choice
     */
    public Choice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPassengerButton = new javax.swing.JButton();
        AddBusButton = new javax.swing.JButton();
        BookTicketButton = new javax.swing.JButton();
        HeadLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking::Options");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        AddPassengerButton.setBackground(new java.awt.Color(102, 255, 0));
        AddPassengerButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        AddPassengerButton.setForeground(new java.awt.Color(0, 0, 255));
        AddPassengerButton.setText("PASSENGER MANAGEMENT");
        AddPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddPassengerButton);
        AddPassengerButton.setBounds(420, 170, 350, 70);

        AddBusButton.setBackground(new java.awt.Color(102, 255, 0));
        AddBusButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        AddBusButton.setForeground(new java.awt.Color(0, 0, 255));
        AddBusButton.setText("BUS MANAGEMENT");
        AddBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddBusButton);
        AddBusButton.setBounds(420, 250, 350, 70);

        BookTicketButton.setBackground(new java.awt.Color(102, 255, 0));
        BookTicketButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        BookTicketButton.setForeground(new java.awt.Color(0, 0, 255));
        BookTicketButton.setText("BOOK TICKETS");
        BookTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicketButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BookTicketButton);
        BookTicketButton.setBounds(420, 340, 350, 70);

        HeadLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadLabel.setText("  BUS RESERVATION SYSTEM");
        HeadLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HeadLabel.setOpaque(true);
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(0, 10, 1080, 60);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 110, 130, 43);

        LogoutButton.setBackground(new java.awt.Color(255, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton);
        LogoutButton.setBounds(540, 440, 120, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        Background.setAlignmentY(0.0F);
        Background.setName("background"); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void AddPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerButtonActionPerformed
      
        
        new PassengerManagement().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPassengerButtonActionPerformed

    private void AddBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBusButtonActionPerformed
        new BusManagement().setVisible(true);
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBusButtonActionPerformed

    private void BookTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicketButtonActionPerformed
       new BookTicket().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTicketButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed

        new Login().setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBusButton;
    private javax.swing.JButton AddPassengerButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton BookTicketButton;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
