/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iliyas
 */

import javax.swing.JOptionPane;
import com.mysql.jdbc.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

public class DisplayBus extends javax.swing.JFrame {

    
     Connection conn = null;
     PreparedStatement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form DisplayBus
     */
    public DisplayBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayBusTable = new javax.swing.JTable();
        DisplayAll = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        SearchTextbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        HeadLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking::Bus List");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton5.setText("<< BACK");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 50, 100, 60);

        jLabel1.setBackground(new java.awt.Color(0, 0, 240));
        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ADDED BUSES LIST");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 50, 330, 70);

        DisplayBusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Reg. No", "Bus type", "Max Seats", "Seats Available", "Dep. City", "Arrival City", "Dep. date", "Dep. Time", "Arr. Time", "Distance", "Fare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DisplayBusTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 1080, 520);

        DisplayAll.setText("Display All");
        DisplayAll.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayAll);
        DisplayAll.setBounds(730, 150, 110, 30);

        Search.setText("SEARCH");
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(600, 150, 80, 30);

        SearchTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextboxActionPerformed(evt);
            }
        });
        SearchTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchTextboxKeyTyped(evt);
            }
        });
        getContentPane().add(SearchTextbox);
        SearchTextbox.setBounds(400, 150, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Bus Reg. No :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 150, 160, 30);

        HeadLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel.setText("                        BUS RESERVATION SYSTEM");
        HeadLabel.setOpaque(true);
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(0, 0, 1080, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        Background.setAlignmentY(0.0F);
        Background.setName("background"); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        new BusManagement().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllActionPerformed
        conn = MysqlConnect.connectDB();
        try
        {
            DefaultTableModel model = (DefaultTableModel)DisplayBusTable.getModel();
            model.setRowCount(0);
            ps=conn.prepareStatement("SELECT * FROM bus");
            rs = ps.executeQuery();
            while(rs.next())
            {
                String busno = rs.getString(1);
                String bustype = rs.getString(2);
                String maxseats = rs.getString(3);
                String noseats = rs.getString(4);
                String depcity = rs.getString(5);
                String arrcity = rs.getString(6);
                String depdate = rs.getString(7);
                String deptime = rs.getString(8);
                String arrtime = rs.getString(9);
                String distance = rs.getString(10);
                String fare = rs.getString(11);
                model.addRow(new Object[] {busno,bustype,maxseats,noseats,depcity,arrcity,depdate,deptime,arrtime ,distance,fare,});
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayAllActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
         conn = MysqlConnect.connectDB();
       
         String gid=SearchTextbox.getText();
         
         try
        {
            DefaultTableModel model = (DefaultTableModel)DisplayBusTable.getModel();
            model.setRowCount(0);
            ps=conn.prepareStatement("SELECT * FROM bus where bus_no=?");
            ps.setString(1,gid);
            rs = ps.executeQuery();
            if(rs.next())
            {
                String busno = rs.getString(1);
                String bustype = rs.getString(2);
                String maxseats = rs.getString(3);
                String noseats = rs.getString(4);
                String depcity = rs.getString(5);
                String arrcity = rs.getString(6);
                String depdate = rs.getString(7);
                String deptime = rs.getString(8);
                String arrtime = rs.getString(9);
                String distance = rs.getString(10);
                String fare = rs.getString(11);
                model.addRow(new Object[] {busno,bustype,maxseats,noseats,depcity,arrcity,depdate,deptime,arrtime ,distance,fare,});
            }
                else
            {
                JOptionPane.showMessageDialog(null,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Bus Details Not Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextboxActionPerformed

    private void SearchTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextboxKeyTyped
        
         char keyChar = evt.getKeyChar();
    if (Character.isLowerCase(keyChar)) {
      evt.setKeyChar(Character.toUpperCase(keyChar));
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton DisplayAll;
    private javax.swing.JTable DisplayBusTable;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchTextbox;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
