/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.jdbc.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;



/**
 *
 * @author Iliyas
 */
public class Login extends javax.swing.JFrame {

    
    Connection conn= null;
    PreparedStatement ps=null;
    ResultSet rs=null;

            
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new javax.swing.JButton();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextbox = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginIcon = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        Showpwdlabel = new javax.swing.JLabel();
        HeadLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking : : Login");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("LoginFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        LoginButton.setBackground(new java.awt.Color(0, 255, 0));
        LoginButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 0, 204));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(460, 590, 150, 60);

        UsernameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username");
        getContentPane().add(UsernameLabel);
        UsernameLabel.setBounds(330, 390, 140, 60);

        PasswordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password");
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(340, 450, 140, 50);

        UsernameTextbox.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        getContentPane().add(UsernameTextbox);
        UsernameTextbox.setBounds(510, 400, 140, 40);

        PasswordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(510, 460, 140, 40);

        LoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        getContentPane().add(LoginIcon);
        LoginIcon.setBounds(350, 50, 290, 330);

        checkbox.setBackground(new java.awt.Color(0, 0, 0));
        checkbox.setAlignmentY(0.0F);
        checkbox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkbox.setMaximumSize(new java.awt.Dimension(30, 30));
        checkbox.setMinimumSize(new java.awt.Dimension(30, 30));
        checkbox.setPreferredSize(new java.awt.Dimension(30, 30));
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox);
        checkbox.setBounds(510, 520, 20, 20);

        Showpwdlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        Showpwdlabel.setForeground(new java.awt.Color(255, 255, 255));
        Showpwdlabel.setText("Show Password");
        getContentPane().add(Showpwdlabel);
        Showpwdlabel.setBounds(540, 520, 107, 20);

        HeadLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadLabel.setText("   WELCOME TO BUS RESERVATION SYSTEM");
        HeadLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HeadLabel.setOpaque(true);
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(0, 0, 1080, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        Background.setAlignmentY(0.0F);
        Background.setName("background"); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
                       
        conn = MysqlConnect.connectDB();
        String Sql= "Select * from login where username = ? and password = ?" ;
        try{
            
            //JOptionPane.showMessageDialog(null,"Login ");
            ps=conn.prepareStatement(Sql);
            ps.setString(1,UsernameTextbox.getText());
            ps.setString(2,PasswordField.getText());
            rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(null,"rs = " + rs);
            if (rs.next())
            {
                new Choice().setVisible(true);
                this.setVisible(false);
            }
                else
            {
                JOptionPane.showMessageDialog(null,"Login Failed!! Please check your credentials","ALERT", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
               
        
//        String pwd = new String(PasswordField.getPassword());
//        if(UsernameTextbox.getText().equals("admin")&&pwd.equals("admin123"))
//        {
//            
//            new Choice().setVisible(true);
//            this.setVisible(false);
//            //JOptionPane.showMessageDialog(null,"Login Successfull");
//        }
//        else
//        {
//         JOptionPane.showMessageDialog(null,"Login Failed!! Please check your credentials");      
//         }
// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
     if (checkbox.isSelected())
        {
            PasswordField.setEchoChar((char)0); 
        }
    else
        {

            PasswordField.setEchoChar('*');
        }  
    

// TODO add your handling code here:
    }//GEN-LAST:event_checkboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginIcon;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel Showpwdlabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextbox;
    private javax.swing.JCheckBox checkbox;
    // End of variables declaration//GEN-END:variables
}
