/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import com.mysql.jdbc.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Iliyas
 */
public class PrintTicket extends javax.swing.JFrame {

     Connection conn = null;
     PreparedStatement ps=null;
    ResultSet rs=null;
    String Vno="[0-9]*";
    int tid;
    /**
     * Creates new form PrintTicket
     */
    public PrintTicket() {
        initComponents();
        onStart();
    }

 
    private void onStart(){
    conn = MysqlConnect.connectDB();

        //String gid=SearchTextbox.getText();

        try
        {
            ps=conn.prepareStatement("SELECT Max(ticket_id) FROM ticket_view");
            rs = ps.executeQuery();
            if(rs.next())
            {
                String tid1 = rs.getString(1);
                int tid2 = Integer.parseInt(tid1);
                try
                {
                    ps=conn.prepareStatement("SELECT * FROM ticket_view where ticket_id =?");
                    ps.setInt(1,tid2); 
                    rs = ps.executeQuery();
                        if(rs.next())
              
            {

                String tid = rs.getString(1);
                String pid = rs.getString(2);
                String bdate= rs.getString(4);
                String busno = rs.getString(3);
                String bustype = rs.getString(9);
                String noseats = rs.getString(5);
                String depcity = rs.getString(11);
                String arrcity = rs.getString(12);
                String depdate = rs.getString(13);
                String deptime = rs.getString(14);
                String arrtime = rs.getString(15);
                String btype = rs.getString("bus_type");
                String total = rs.getString(7);
                String fare = rs.getString("Fare");
                String gender = rs.getString("gender");
                String mobno = rs.getString("mobno");
                String age = rs.getString("age");
                String fname = rs.getString("Fname");
                String mname = rs.getString("Mname");
                String lname = rs.getString("Lname");
                String name=fname +" "+ mname + " "+lname;

                TicketIDLabel.setText(tid);
                PNameLabel.setText(name);
                BDateLabel.setText(bdate);
                BTypeLabel.setText(btype);
                DepCityLabel.setText(depcity);
                ArrCityLabel.setText(arrcity);
                DepTimeLabel.setText(deptime);
                ArrTimeLabel.setText(arrtime);
                DOJLabel.setText(depdate);
                GenderLabel.setText(gender);
                MobNoLabel.setText(mobno);
                AgeLabel.setText(age);
                FareLabel.setText(fare);
                NoSeatsLabel.setText(noseats);
                BusNoLabel.setText(busno);
                TotalLabel.setText(total);
                PIDLabel.setText(pid);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Bus Details Not Found Inner catch" +e, "Error", JOptionPane.ERROR_MESSAGE);
        }
            }       
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Bus Details Not Found " +e, "Error", JOptionPane.ERROR_MESSAGE);
        }
                
        // TODO add your handling code here:
    }                          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MobNoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ArrTimeLabel = new javax.swing.JLabel();
        FareLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DepTimeLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        BusNoLabel = new javax.swing.JLabel();
        DepCityLabel = new javax.swing.JLabel();
        PIDLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TicketIDLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ArrCityLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PNameLabel = new javax.swing.JLabel();
        BTypeLabel = new javax.swing.JLabel();
        BDateLabel = new javax.swing.JLabel();
        DOJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NoSeatsLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        HeadLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BusBooking::PrintTicket");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ticket ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 190, 95, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Booking Date :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 190, 145, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Passenger Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 320, 164, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Fare per Seat :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 510, 132, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Bus Type :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(610, 550, 110, 40);

        GenderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(GenderLabel);
        GenderLabel.setBounds(720, 320, 150, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Date of Journey :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 240, 156, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Contact Number :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 370, 160, 30);

        MobNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(MobNoLabel);
        MobNoLabel.setBounds(400, 370, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Arrival City :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(590, 410, 111, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Gender :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(620, 320, 88, 30);

        ArrTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ArrTimeLabel);
        ArrTimeLabel.setBounds(720, 460, 160, 30);

        FareLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(FareLabel);
        FareLabel.setBounds(390, 510, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Age :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 360, 54, 30);

        DepTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(DepTimeLabel);
        DepTimeLabel.setBounds(400, 460, 160, 30);

        AgeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(AgeLabel);
        AgeLabel.setBounds(710, 360, 160, 30);

        BusNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BusNoLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(BusNoLabel);
        BusNoLabel.setBounds(390, 550, 170, 30);

        DepCityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(DepCityLabel);
        DepCityLabel.setBounds(400, 410, 160, 30);

        PIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(PIDLabel);
        PIDLabel.setBounds(410, 280, 120, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("No of Seats :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(590, 510, 114, 30);

        TotalLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(TotalLabel);
        TotalLabel.setBounds(460, 630, 110, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Arrival Time :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(580, 460, 130, 30);

        TicketIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(TicketIDLabel);
        TicketIDLabel.setBounds(400, 190, 90, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Bus No :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(290, 550, 90, 30);

        ArrCityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ArrCityLabel);
        ArrCityLabel.setBounds(720, 410, 160, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Departing Time :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 460, 151, 30);

        PNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(PNameLabel);
        PNameLabel.setBounds(400, 320, 200, 30);

        BTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(BTypeLabel);
        BTypeLabel.setBounds(720, 550, 160, 40);

        BDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(BDateLabel);
        BDateLabel.setBounds(720, 190, 160, 30);

        DOJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(DOJLabel);
        DOJLabel.setBounds(400, 240, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Departure City :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 410, 144, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Total Amount paid :  ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(210, 620, 250, 58);

        NoSeatsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(NoSeatsLabel);
        NoSeatsLabel.setBounds(720, 510, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Passenger ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 280, 129, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton5.setText("<< BACK");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 70, 100, 60);

        HeadLabel.setBackground(new java.awt.Color(0, 0, 0));
        HeadLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(204, 255, 0));
        HeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadLabel.setText("  BUS RESERVATION SYSTEM");
        HeadLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HeadLabel.setOpaque(true);
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(0, 0, 1080, 60);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TICKET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 90, 170, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        new BookTicket().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel ArrCityLabel;
    private javax.swing.JLabel ArrTimeLabel;
    private javax.swing.JLabel BDateLabel;
    private javax.swing.JLabel BTypeLabel;
    private javax.swing.JLabel BusNoLabel;
    private javax.swing.JLabel DOJLabel;
    private javax.swing.JLabel DepCityLabel;
    private javax.swing.JLabel DepTimeLabel;
    private javax.swing.JLabel FareLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JLabel MobNoLabel;
    private javax.swing.JLabel NoSeatsLabel;
    private javax.swing.JLabel PIDLabel;
    private javax.swing.JLabel PNameLabel;
    private javax.swing.JLabel TicketIDLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
